import Link from "next/link";
import Image from "next/image";
import { db } from "@/lib/db";
import { ProductCard } from "@/components/product-card";
export default async function Home() {
  const products = await db.product.findMany({ orderBy: { id: "asc" } });
  return <>
    <section className="hero"><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow">Muara Baru, Jakarta — sejak 2022</p><h1>Dari sumber lokal.<br />Untuk kebutuhan<br /><em>bisnis Anda.</em></h1><p className="hero-description">Pengadaan komoditas ikan dengan sourcing fleksibel dan dukungan cold chain. Temukan produk yang tersedia, lalu ajukan kebutuhan Anda kepada AJS.</p><div className="hero-actions"><Link className="button gold" href="/catalog">Lihat komoditas <span aria-hidden>↗</span></Link><Link className="light-link" href="/login">Masuk sebagai buyer →</Link></div><div className="hero-note"><span>01 / SOURCING</span><p>Menghubungkan pasokan lokal<br />dengan kebutuhan pasar.</p></div></div><div className="hero-photo"><Image src="/images/muara-baru.jpg" alt="Aktivitas perdagangan ikan di Muara Baru dari company profile AJS" width={654} height={756} priority /><div className="photo-caption"><span>Sourcing hub utama</span><strong>Muara Baru, Jakarta <span aria-hidden>↗</span></strong></div></div></div></section>
    <section className="capability-strip"><div className="container strip-grid"><div><span>01</span><strong>Flexible sourcing</strong><p>Pengadaan sesuai ketersediaan dan kebutuhan.</p></div><div><span>02</span><strong>Cold-chain access</strong><p>Dukungan fasilitas sewa dan kemitraan.</p></div><div><span>03</span><strong>Hands-on operations</strong><p>Dari sourcing dan handling hingga distribusi.</p></div></div></section>
    <section className="container section"><div className="section-heading"><div><p className="eyebrow">Komoditas pilihan</p><h2>Mulai dari kebutuhan Anda.</h2></div><p>Lihat spesifikasi dan stock tersedia.<br />Setiap request ditinjau oleh tim AJS.</p></div><div className="product-grid">{products.map(p => <ProductCard key={p.id} product={p} />)}</div><p className="fineprint">Data stock dan harga merupakan contoh untuk challenge. Harga final memerlukan konfirmasi AJS.</p></section>
    <section className="supply-section"><div className="container supply-grid"><Image src="/images/cold-storage.jpg" alt="Fasilitas cold storage dalam company profile AJS" width={562} height={310} /><div><p className="eyebrow">Pengadaan dengan konfirmasi</p><h2>Kebutuhan Anda,<br />ditinjau oleh tim kami.</h2><p>Pilih komoditas dan quantity, kirim request, lalu pantau statusnya di portal buyer. Pengiriman request belum merupakan transaksi final.</p><Link className="button" href="/login">Buka portal buyer <span aria-hidden>↗</span></Link></div></div></section>
  </>;
}
